add_newline = false
format = "${custom.cat}$directory$git_branch$git_status$nodejs$python$status$cmd_duration$character"

[custom.cat]
command = '''od -An -N4 -tu4 /dev/urandom | awk '{ cats[0]="🐱"; cats[1]="😺"; cats[2]="😸"; cats[3]="😻"; cats[4]="😼"; cats[5]="😽"; cats[6]="🙀"; cats[7]="🐈"; print cats[$1 % 8] }' '''
when = true
format = "[$output]($style) "
style = "bold yellow"
shell = ["sh"]

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "yellow"

[nodejs]
format = "[node $version]($style) "
style = "green"

[python]
format = "[py $version]($style) "
style = "yellow"

[status]
disabled = false
format = "[$status]($style) "
style = "bold red"

[cmd_duration]
min_time = 1000
format = "[$duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
